export declare global{
  namespace ReactNavigation{
    interface RootParamList{
        Home:undefined;
        SignIn:undefined;
        SignUp:undefined;
        ForgotPassword:undefined;
        CreateProfile:undefined;
        TabNavigation:undefined;
        Books:undefined;
        NewBooks:undefined;
        OldBooks:undefined;
        Genesis:undefined;
        Gn1:undefined;
        Gn2:undefined;
        Gn3:undefined;
        Gn4:undefined;
        Gn5:undefined;
        Gn6:undefined;
        Gn7:undefined;
        Gn8:undefined;
        Gn9:undefined;
        Gn10:undefined;
        Gn11:undefined;
        Gn12:undefined;
        Gn13:undefined;
        Gn14:undefined;
        Gn15:undefined;
        Gn16:undefined;
        Gn17:undefined;
        Gn18:undefined;
        Gn19:undefined;
        Gn20:undefined;
        Gn21:undefined;
        Gn22:undefined;
        Gn23:undefined;
        Gn24:undefined;
        Gn25:undefined;
        Gn26:undefined;
        Gn27:undefined;
        Gn28:undefined;
        Gn29:undefined;
        Gn30:undefined;
        Gn31:undefined;
        Gn32:undefined;
        Gn33:undefined;
        Gn34:undefined;
        Gn35:undefined;
        Gn36:undefined;
        Gn37:undefined;
        Gn38:undefined;
        Gn39:undefined;
        Gn40:undefined;
        Gn41:undefined;
        Gn42:undefined;
        PlayerAudio:{audioId:string};
        Profile:undefined;
        Config:undefined;
        Credits:undefined;
        UpdateName:undefined;
        UpdateEmail:undefined;
      
    }
  }
}